spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/concurrency
    username: root
    password:
    hikari:
      maximum-pool-size: 40
  redis:
    host: localhost
    port: 6379



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

